### ISSUE TITLE
could there be a feature to save while generating？

### ISSUE THREAD

**Issue by ScottishFold007** [argilla-io/distilabel#168]
It's great that this works, but could there be a feature to save while generating, so that the pipeline doesn't go wrong in the middle and the previous data runs in vain?

**Comment by dvsrepo** [comment]
cc @alvarobartt to help out

**Comment by alvarobartt** [comment]
Hi @ScottishFold007! Indeed we included a feature that does checkpointing and recovers everything in case something failed, while not losing anything, are you experiencing issues with it? In the `Pipeline.generate` method there is an arg `enable_checkpoints=True` that does that for you

See the reference at https://distilabel.argilla.io/reference/distilabel/pipeline/

<img width="1624" alt="image" src="https://github.com/argilla-io/distilabel/assets/36760800/af17482a-cade-4376-8478-e011be58b375">

**Comment by alvarobartt** [comment]
If what you mean is to add a feature to save every N iterations, that's something we can try to look into, but may be more complex to handle internally, so another workaround is to batch the dataset and provide smaller batches instead. But as mentioned, the `enable_checkpoints=True` should be working fine and all the generations/labels should be restored if succeeded, while the failed ones will be fulfilled with None.

**Comment by ScottishFold007** [comment]
So, if enable_checkpoints is set to true and fails, how do I use this saved checkpoints? I don't see this written in the tutorial

**Comment by alvarobartt** [comment]
It should be automatic, meaning that as it's enabled by default and the process may fail due to a wide variety of reasons, then you just need to capture the resulting dataset as `dataset = pipeline.generate(..., enable_checkpoints=True)` and then that resulting `datasets.Dataset` will contain all the rows from the original dataset that you provided, and the ones fulfilled will be the ones that succeeded while the rest will have `None` 🤗
