### ISSUE TITLE
[BUG] UltraCMTask fails when using it with OpenAILLM

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#186]
I would expect the UltraCMTask to work with OpenAILLM or at least to throw an error to tell me that this is not supported.

Unfortunately, it fails with the following:

```python
from datasets import Dataset
from distilabel.llm import OpenAILLM
from distilabel.pipeline import Pipeline
from distilabel.tasks.critique.ultracm import UltraCMTask


pipeline = Pipeline(
        labeller=OpenAILLM(
            task=UltraCMTask(),
            model="gpt-4",
            openai_api_key=userdata.get('OPENAI_API_KEY'),
            temperature=1.0,
        ),
    )

dataset = Dataset.from_dict(
        {
            "instruction": ["What's the capital of Spain?"],
            "completion": ["Madrid"],
        }
    )

dataset = pipeline.generate(
        dataset,  # type: ignore
        display_progress_bar=True,
)

#error  
*Format*
### Feedback
Overall Score: [1-10]
[Your feedback]

---
</s>
Assistant: ### Feedback
Overall Score: ` is of `type=<class 'str'>`, but it must be of `type=<class 'list'>`, so make sure that `task.generate_prompt` returns a `<class 'list'>` or that the `formatting_fn` formats the prompt as a  `<class 'list'>`.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
RuntimeError: `Pipeline.generate` failed during labelling step. Setting `enable_checkpoints=True` is recommended!

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/distilabel/pipeline.py](https://localhost:8080/#) in dry_run(self, dataset)
    703         except Exception as e:
    704             self._teardown()
--> 705             raise RuntimeError(
    706                 f"`Pipeline.generate` failed during the dry run over {dataset[0]} with exception: {e}"
    707             ) from e

RuntimeError: `Pipeline.generate` failed during the dry run over {'instruction': "What's the capital of Spain?", 'completion': 'Madrid'} with exception: `Pipeline.generate` failed during labelling step. Setting `enable_checkpoints=True` is recommended!
```

I would assume our tasks should support swapping LLMs, if this is not feasible we need to rethink the interaction between Task and LLM. From what I see other tasks return a Prompt instead of string, and this is a relatively easy to follow prompt and output for OpenAI models, which will allow avoiding the usage of a heavy OSS/local model.

**Comment by alvarobartt** [comment]
Hey, thanks for the issue! Yes, this was something we discussed and we mentioned that it was due to the format being specific to certain models and intended to be used within those models as those are the formats defined specifically for certain models, and in most of the cases those can only be extended to OpenAI as it generalises better, anyway I'll tackle this so that we remove the default formatting and return the `Prompt` instead

IMO we should also remove some LLM-specific tasks such as `Llama2TextGenerationTask` if we always want to return a `Prompt`

At some point we can even consider to make the default format the OpenAI's one, so that we return a list of N items with `role` and `content` and then we parse that ourselves (also related to the multi turn prompting issue).
