### ISSUE TITLE
[FEATURE] Rename UltraFeedback.for_text_quality to for_overall_quality or something similar

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/distilabel#220]
for_text_quality is a bit off because it's really a summary of all other aspects (truthfulness, honesty, etc.) and we're talking about response quality/alignment not general text

**Comment by alvarobartt** [comment]
Fair, but weird because I saw no references to that template format, not even in the official repository at https://github.com/OpenBMB/UltraFeedback/blob/main/src/data_annotation/preference_templates.py neither on the paper.

So my question is, where does that task actually come from? Is it something we introduced but not compliant with the original definition?

**Comment by dvsrepo** [comment]
This is a custom one I created that works pretty well (given our limited benchmarks). The reasoning is that the original Ultrafeedback needed to run 4 times, one for each aspect to get an overall judgement. This one I created summarizes all aspects (similar to judgelm).

**Comment by dvsrepo** [comment]
Additionally, we don't need to be compliant with Ultrafeedback as it's a research work we can build upon and there are few people that really knows the details

**Comment by alvarobartt** [comment]
Cool, thought it came from the paper instead and couldn't find the reference! Then we can go ahead with the change!

Should it be `for_text_quality` -> `for_overall_quality`?
