### ISSUE TITLE
[FEATURE] Thinking of adding a GroqLLM integration to distilabel

### ISSUE THREAD

**Issue by kcentric** [argilla-io/distilabel#348]
[Groq](https://wow.groq.com/why-groq/) is a startup developing LPU engines which provide 18x faster inference than GPUs. They currently provide Llama2-70B via API, and Mixtral 8x7B access on request. It would be great to add a `GroqLLM` module to distilabel just like we have `OpenAILLM`. I've been trying out their platform and it's 🔥 . 

It shouldn't be too difficult because they already try to make switching from OpenAI to Groq API easy.

**Comment by alvarobartt** [comment]
Yes, Groq is lightning fast and we're aware of it! We're now going through a `distilabel` refactor, but for sure that's something we'll have into consideration and try to implement as part of the v1.0 later this month. Thanks for the proposal!

**Comment by alvarobartt** [comment]
So we saw some limitations on certain scenarios and we're now trying to provide more flexibility, so we decided to refactor it and ship it as v1.0, that's why we won't be releasing minor releases until the refactor is done (expect it by the end of the month more or less). But sure, if you're willing to contribute feel free to include it, as `LLM` won't change much so would be appreciated and useful! Just let me know if you need any other detail 👍🏻

**Comment by dvsrepo** [comment]
@kcentric adding GroqLLM now would be super cool indeed, that means we and the community can start testing it right away!

**Comment by kcentric** [comment]
Thanks guys! I'll get to work on it and see what I can do 🙂
