### ISSUE TITLE
[FEATURE] show raw input/response within tasks

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/distilabel#698]
**Is your feature request related to a problem? Please describe.**
I was experiencing some uncertainty when making calls to my expensive GPT4 model w.r.t. the actual prompts I was sending to it. You might want to disable this for memory purposes but I think it would be good to have the formatted prompts available or accessible somewhere during pipeline/project iteration.

**Describe the solution you'd like**
An optional flag to show `raw_output` and/or `raw_input` 

**Describe alternatives you've considered**
N.A. 

**Additional context**
N.A.

**Comment by gabrielmbmb** [comment]
There is an [`add_raw_output`](https://distilabel.argilla.io/dev/sections/learn/tutorial/task/#working-with-tasks) flag that since `1.2.0` is going to have a default value of `True`. This will add a `raw_output` in the `distilabel_metadata` dictionary.

For the `raw_input`, we can do the same, add a `add_raw_input` flag.
